### ISSUE TITLE
Any plans on compatibility with other DEs?

### ISSUE THREAD

**Issue by negzersqu** [centic9/headset-charge-indicator#2]
Hi! HeadsetControl is super useful, but I'd love to be able to see the battery without opening a terminal. However, I couldn't get it to work on the latest version of Plasma. Any workaround for making it work on DEs other than Gnome?
Thanks

**Comment by centic9** [comment]
Do you have a link to how the equivalent functionality can be done for Plasma? Ideally with python-bindings?

I did a quick test on Ubuntu Focal and it seems there is actually some support in Plasma for appindicators. The icon appears, only the battery level is not printed, seems Plasma does not support adding text via "set_label".

**Comment by scotbud123** [comment]
So this only works on GNOME? Would getting it to work on Cinnamon be difficult?

**Comment by centic9** [comment]
Unfortunately I don't use Cinnamon at all so cannot say from my side.

I am in general interested in adding support for other desktop systems if they support a similar indicator system as long as there is an Python API available (C-API might also work via some C-to-Python bridge. 

Any pointers to information or summary of experience when trying to get it to work is welcome!

**Comment by centic9** [comment]
Actually after a quick try in a virtual machine it seems to work fine if you just follow the normal installation steps, only the percentage display was not visible, maybe Cinnamon indicators do not support displaying text along the icon:

![Bildschirmfoto von 2020-07-02 07-34-18](https://user-images.githubusercontent.com/548322/86320216-a9212900-bc36-11ea-8752-a7d4e2da5243.png)

**Comment by centic9** [comment]
I have now tested a number of different window manages, Cinnamon and KDE/Plasma seem to be able to run the tool and show the icon, however both do not show the percentage, likely due to missing support for adding text next to appindicator icons in the panel.

See https://github.com/centic9/headset-charge-indicator/blob/master/README.md#supported-desktop-envrionemnts for the list that I tried quickly.

Let me know if you have any additional information or changes that can be made to improve support for other desktop-environments.
