### ISSUE TITLE
Not working with Corsair Void Pro Wireless

### ISSUE THREAD

**Issue by demian711** [centic9/headset-charge-indicator#3]
Hello.
I'm using Ubuntu 18.04 and a Corsair Void Pro Wireless.
headsetcontrol is working just fine, but 'headset-charge-indicator' is failing because this headset doesn't support chat-mix.

`sudo python3 headset-charge-indicator.py /usr/local/bin/headsetcontrol
Bat: 54
Error: This headset doesn't support chat-mix level
Command '['/usr/local/bin/headsetcontrol', '-m', '-c']' returned non-zero exit status 1.
Bat: 54
Error: This headset doesn't support chat-mix level
Command '['/usr/local/bin/headsetcontrol', '-m', '-c']' returned non-zero exit status 1.
`
Is there a why to bypass this and make it work?

thanks

**Comment by demian711** [comment]
So, I commented out any reference to chatmix in the python file, but then after running The program with:

`sudo python3 headset-charge-indicator.py /usr/local/bin/headsetcontrol`

Im getting the battery percentage in screen but no icon in top bar:

`sudo python3 headset-charge-indicator.py /usr/local/bin/headsetcontrol
Bat: 52

Bat: 52
`
If I run headset-charge-indicator.py without specifying the headsetcontrol binary, of course it shows no options but the icon and menu appears in top bar.

**Comment by centic9** [comment]
I don't think the chatmix function should be related as the "unavailable"-exception is properly contained and logged there. If I make it fail locally for me, the icon/app-indicator still works fine.

Which exact desktop-environment are you using? I tried a few and some were not working well for some reason, see also the section in the README of this repository.

**Comment by rtaft** [comment]
I just went through this, though I'm still not 100% as I just have ellipses on my system tray but I got past where you are stuck.  Removing the sudo should get you the system tray icon, but it still won't work as is because the udev file doesnt have all devices in it.
Run `lsusb`
Get the corsair product ID
Edit `/etc/udev/rules.d/70-headsets.rules`
Look for the corsair entries, they all have the vendor ID `1b1c`.  In my case I had to add another line for the product `0a16`, it has 14 and 17 but not 16.
Run `sudo udevadm control --reload-rules && sudo udevadm trigger`
Now you should be able to run headsetcontrol without sudo, which will allow this python script to work.
The chat-mix error is OK, it just disables chat-mix in the system tray menu.

**Comment by centic9** [comment]
I think this is either solved by the previous comment or actually a problem of installing HeadsetControl properly for non-root usage via correct udev rules. 

If this is still a problem for you then please discuss this via an Issue at https://github.com/Sapd/HeadsetControl/
